// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initial1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial1));
        
        string IMigrationMetadata.Id
        {
            get { return "201310112018326_initial1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
